// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/geoiq-logo/AppIcon.tsx": () => import("../components/mockups/geoiq-logo/AppIcon.tsx"),
  "./components/mockups/geoiq-logo/GeoIQLogo.tsx": () => import("../components/mockups/geoiq-logo/GeoIQLogo.tsx"),
  "./components/mockups/geoiq-logo/LightDark.tsx": () => import("../components/mockups/geoiq-logo/LightDark.tsx"),
  "./components/mockups/geoiq-logo/Wordmark.tsx": () => import("../components/mockups/geoiq-logo/Wordmark.tsx")
};
